In [22]:
import pandas as pd
import re
import math

apt_filename = "apartments.csv"
domu_filename = "domu.csv"
apt = pd.read_csv(apt_filename, dtype='string')
domu = pd.read_csv(domu_filename, dtype='string')

Change Apartments and Domu Dataframe into consistent formatting

In [23]:
apt = apt.replace({"room_area": ","}, {"room_area": ""}, regex=True)

In [24]:
apt

,property_name,address,latitude,longitude,price_range,bedroom,bathroom,room_area,amenities
0,The Residences at NewCity,"1457 N Halsted St, Chicago IL 60642",41.90801,-87.64773,"$2,126 - $4,215",Studio - 2 bd,1 - 2 ba,590 - 1315 sq ft,"Pool, Fitness Center, Elevator, Clubhouse, Con..."
1,Elevate,"930 W Altgeld St, Chicago IL 60614",41.9276,-87.65243,"$1,910 - $14,435",Studio - 3 bd,1 - 2.5 ba,464 - 2616 sq ft,"Pool, Fitness Center, Elevator, Clubhouse, In ..."
2,1407 On Michigan,"1407 S Michigan Ave, Chicago IL 60605",41.86377,-87.6236,"$1,750 - $5,650",Studio - 3 bd,1 - 2 ba,446 - 1687 sq ft,"Pool, Fitness Center, Elevator, Doorman, Clubh..."
3,The Pavilion,"5441 NE NEast River Rd, Chicago IL 60656",41.97831,-87.84335,"$1,115 - $2,420",Studio - 4 bd,1 - 3 ba,502 - 2317 sq ft,"Pool, Fitness Center, Controlled Access, Busin..."
4,Gild,"1206-1212 N State Pky, Chicago IL 60610",41.90423,-87.62905,"$2,260 - $6,322",Studio - 2 bd,1 - 2 ba,463 - 1272 sq ft,"Fitness Center, Elevator, Concierge, Clubhouse..."
...,...,...,...,...,...,...,...,...,...
695,8053 S Essex Ave,"8053 S Essex Ave, Chicago IL 60617",41.74842,-87.5634,"$1,150",2 bd,1 ba,1100 sq ft,"Hardwood Floors, Office, Smoke Free, Dining Room"
696,2543 S Springfield Ave,"2543 S Springfield Ave, Chicago IL 60623",41.84484,-87.72177,"$1,425",3 bd,1 ba,900 sq ft,"Air Conditioning, Dishwasher, Island Kitchen, ..."
697,937 E Hyde Park Blvd Unit 3,"937 E Hyde Park Blvd, Chicago IL 60615",41.80198,-87.60244,"$1,588",2 bd,1 ba,1016 sq ft,"Air Conditioning, Dishwasher, Hardwood Floors,..."
698,711 W Brompton Ave,"711 W Brompton Ave, Chicago IL 60657",41.94648,-87.64703,"$1,550",1 bd,1 ba,700 sq ft,"In Unit Washer & Dryer, Air Conditioning, Dish..."
699,1850 S Ridgeway Ave,"1850 S Ridgeway Ave, Chicago IL 60623",41.8556,-87.71913,"$1,400",3 bd,1 ba,850 sq ft,"In Unit Washer & Dryer, Air Conditioning, Hard..."

In [25]:
domu["bedroom"] = domu["bedroom"].str.lower()
domu = domu.replace({"bedroom": "0 - 0 bed"}, {"bedroom": "Studio"}, regex=True)
domu = domu.replace({"bedroom": "0"}, {"bedroom": "Studio"}, regex=True)
domu = domu.replace({"bedroom": "bed"}, {"bedroom": "bd"}, regex=True)
domu = domu.replace({"address": "Chicago, IL,"}, {"address": "Chicago IL"}, regex=True)
domu = domu.replace({"amenities": "In-unit Laundry"}, {"amenities": "In Unit Washer & Dryer"}, regex=True)

domu["bathroom"] = domu["bathroom"].str.lower()
domu = domu.replace({"bathroom": "bath"}, {"bathroom": "ba"}, regex=True)

In [26]:
domu

,property_name,address,latitude,longitude,price_range,bedroom,bathroom,room_area,amenities
0,NEMA Chicago Apartments,"1210 S Indiana Ave, Chicago IL 60605",41.866998,-87.62338,"$1,777â€“$19,900",Studio - 4 bd,1 - 4 ba,420 - 2703 sq ft,"Pet Friendly, Parking Available, Air Condition..."
1,Germain House Apartments,"729 N Sangamon St, Chicago IL 60642",41.895896,-87.651175,"$2,395â€“$3,592",1 - 2 bd,1 - 2 ba,560 - 1065 sq ft,"Pet Friendly, Parking Available, Air Condition..."
2,Porte Apartments,"855 W Madison St, Chicago IL 60607",41.881742,-87.649106,"$2,150â€“$6,700",Studio - 3 bd,1 - 2 ba,546 - 1930 sq ft,"Pet Friendly, Air Conditioning, In Unit Washer..."
3,596 West Hawthorne Apartments,"596 W Hawthorne Pl, Chicago IL 60657",41.94419,-87.645133,"$1,073â€“$1,212",Studio,1 - 1 ba,275 - 330 sq ft,Pet Friendly
4,Three Old Town Park Apartments,"228 W Hill St, Chicago IL 60610",41.902363,-87.635832,"$2,105â€“$8,500",Studio - 2 bd,1 - 2 ba,505 - 2056 sq ft,"Pet Friendly, Parking Available, Air Condition..."
...,...,...,...,...,...,...,...,...,...
302,"1 bedroom Apartment, Skokie","8042 Knox Ave #3B, Skokie, IL, 60076",42.027402,-87.744207,"$1,175",1 bd,1 ba,915 sq ft,"Parking Available, Air Conditioning, Utilities..."
303,"1 bedroom Apartment, Printer's Row","619 S Lasalle St #712, Chicago IL 60605",41.87398,-87.631364,"$1,850",1 bd,1 ba,690 sq ft,"Pet Friendly, Parking Available, Air Condition..."
304,"1 bedroom Apartment, West Loop","123 N Des Plaines St #1414, Chicago IL 60661",41.883618,-87.643776,"$2,672",1 bd + den,1 ba,844 sq ft,"Pet Friendly, Parking Available, Air Condition..."
305,"1 bedroom Apartment, River North","905 N Orleans St #1011, Chicago IL 60610",41.89926,-87.637025,"$2,400",1 bd,1 ba,796 sq ft,"Pet Friendly, Air Conditioning, In Unit Washer..."
306,"1 bedroom Apartment, Logan Square","2340 N California Ave #ID478, Chicago IL 60647",41.924227,-87.698228,"$2,660",1 bd,1 ba,700 sq ft,"Pet Friendly, Air Conditioning, In Unit Washer..."

Combine the two dataframes

In [27]:
housing = pd.DataFrame(columns=[
    "property_name", 
    "address", 
    "latitude", 
    "longitude", 
    "price_range", 
    "bedroom", 
    "bathroom", 
    "room_area",
    "amenities"]
    )

In [28]:
domu_lst = []

for a, arow in apt.iterrows():
    for d, drow in domu.iterrows():
        address_apt = (arow[1].replace(',', '')).lower()
        address_domu = (drow[1].replace(',', '')).lower()
        #bacause only domu has patters like '#' or '-'
        d_add = re.findall(r'#\w+|-\d+', drow[1]) 
        if d_add != []:
            for patterns in d_add:
                address_domu = address_domu.replace(d_add[0].lower(), '')
            address_domu = re.sub(r'[^\w]+', ' ',address_domu).strip() 

        if address_apt == address_domu:
            domu_lst.append(d)

            #check price_range
            if arow["price_range"] == "Call for Rent":
                aprice_low, aprice_high = math.inf, -math.inf
            else:
                aprice = [float(v) for v in arow["price_range"].replace("$", "").replace(",", "").split(" - ")]
                aprice_low, aprice_high = aprice[0], aprice[-1]
            dprice = [float(v) for v in drow["price_range"].replace("$", "").replace(",", "").split("â€“")]
            dprice_low, dprice_high = dprice[0], dprice[-1]

            if dprice_low < aprice_low:
                price_low = drow["price_range"].split("â€“")[0]
            else:
                price_low = arow["price_range"].split(" - ")[0]
            
            if dprice_high > aprice_high:
                price_high = drow["price_range"].split("â€“")[-1]
            else:
                price_high = arow["price_range"].split(" - ")[-1]
            
            if price_low != price_high:
                arow["price_range"] = str(price_low) + " - " + str(price_high)
            else:
                arow["price_range"] = str(price_low)

            #check bedroom
            abd = [int(v) for v in arow["bedroom"].replace("Studio", "0").replace(" bd", "").split(" - ")]
            dbd = [int(v) for v in drow["bedroom"].replace("Studio", "0").replace(" + den", "").replace(" bd", "").split(" - ")]
            abd_low, abd_high = abd[0], abd[-1]
            dbd_low, dbd_high = dbd[0], dbd[-1]

            if min(abd_low, dbd_low) == max(abd_high, dbd_high):
                arow["bedroom"] = str(min(abd_low, dbd_low))
            else:
                arow["bedroom"] = str(min(abd_low, dbd_low)) + " - " + str(max(abd_high, dbd_high)) + " bd"
            if " + den" in drow["bedroom"]:
                arow["bedroom"] += " + den"
            arow ["bedroom"] = arow["bedroom"].replace("0 bd", "Studio").replace("0", "Studio")

            #check bathroom
            aba = [float(v) for v in arow["bathroom"].replace(" ba", "").split(" - ")]
            dba = [float(v) for v in drow["bathroom"].replace(" ba", "").split(" - ")]
            aba_low, aba_high = aba[0], aba[-1]
            dba_low, dba_high = dba[0], dba[-1]

            if min(aba_low, dba_low) == max(aba_high, dba_high):
                arow["bathroom"] = str(min(aba_low, dba_low))
            else:
                arow["bathroom"] = str(min(aba_low, dba_low)) + " - " + str(max(aba_high, dba_high)) + " ba"

            #check room_area
            if not pd.isnull(arow["room_area"]):
                aarea = [int(v) for v in arow["room_area"].replace(" sq ft", "").split(" - ")]
                aarea_low, aarea_high = aarea[0], aarea[-1]
            else:
                aarea_low, aarea_high = math.inf, -math.inf
            darea = [int(v) for v in drow["room_area"].replace(" sq ft", "").split(" - ")]
            darea_low, darea_high = darea[0], darea[-1]

            if min(aarea_low, darea_low) == max(aarea_high, darea_high):
                arow["room_area"] = str(min(aarea_low, darea_low)) + " sq ft"
            else:
                arow["room_area"] = str(min(aarea_low, darea_low)) + " - " + str(max(aarea_high, darea_high)) + " sq ft"

            #check amenities
            apt_amenities = arow["amenities"].split(", ")
            domu_amenities = drow["amenities"].split(", ")
            amenities = list(set(apt_amenities + domu_amenities))
            arow["amenities"] = ", ".join(amenities)
    
    housing.loc[housing.shape[0]] = arow

In [29]:
housing = pd.concat([housing, domu.drop(domu_lst)])
housing.to_csv("combined_housing.csv", index=False)